# Numpy Introduction

In [2]:

pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [95]:
a = np.arange(7)
print(a)
a.shape

[0 1 2 3 4 5 6]


(7,)

In [83]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5 6]]


(1, 7)

# Assignment : why do we have 1D, 2D or 3D arrays and where we need them in Data Science?

In [84]:
a = np.array([1, 2, 3,4, 5, 6])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (8, 9, 10, 11, 12, 13, 14)])

In [85]:
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [86]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

# initialize arrays

In [87]:
zeros = np.zeros((3, 4)) # (rows, columns)
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
ones = np.ones((2, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
full = np.full((2, 5), 5)
print(full)

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [66]:
identity = np.eye(5) # creating an identity matrix
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
a.shape # give us the number elements in array

(6,)

In [68]:
len(a) # give us the length of array

6

In [69]:
b.ndim # give us the dimension of array

2

In [70]:
a.size # give us the number of elements in array

6

# Basic Operations

In [96]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [94]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [97]:
g = a - b
g

array([[-1, -1, -1, -1, -1, -1, -1],
       [-8, -8, -8, -8, -8, -8, -8]])

In [98]:
h = a + b
h

array([[ 1,  3,  5,  7,  9, 11, 13],
       [ 8, 10, 12, 14, 16, 18, 20]])

In [99]:
h1 = np.add(a, b)
h1

array([[ 1,  3,  5,  7,  9, 11, 13],
       [ 8, 10, 12, 14, 16, 18, 20]])

In [100]:
j = a/b
j

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
        0.83333333, 0.85714286],
       [0.        , 0.11111111, 0.2       , 0.27272727, 0.33333333,
        0.38461538, 0.42857143]])