# Numpy (Part 2)

In [1]:
import numpy as np

In [5]:
empty = np.empty((3, 4))
print(empty)
print('--------------')
print(empty[0])

[[1.00903894e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [8.45599365e-307 3.76965195e-061 3.59967689e+179 2.77010042e-057]
 [8.06890180e+169 9.73084790e-072 3.08735795e-057 1.43830482e-051]]
--------------
[1.00903894e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]


In [7]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [8]:
# array of even number from 0 to 23 
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [9]:
# array of odd number from 0 to 23 
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [10]:
# specific diffrence between numbers
diff = np.arange (0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [12]:
lin = np.linspace(0, 20, num=10)
lin


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
lin.dtype 

dtype('float64')

In [16]:
# difine the data type of array
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

# **Assignment** what is the difference between int32, 64 ya float 32, 64,16 ...... what is the meaning of int64


# **Assignment** what is the difference between int32, 64 ya float 32, 64,16 ...... what is the meaning of int64

In [18]:
# sorting an array
arr = np.array([3, 1, 2, 5, 4])
arr

array([3, 1, 2, 5, 4])

In [20]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5])

In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6 , 7, 8, 9, 10])

In [23]:
# concatenate these arrays
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Conatenate 2D Arrays

In [33]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([5, 6]) # 1x2 array

In [30]:
# concatinate 2D arrays
z = np.concatenate((x, [y]), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
w = np.array([[5,1], [3,4]])

In [37]:
z1 = np.concatenate((x, w), axis=1)
z1

array([[1, 2, 5, 1],
       [3, 4, 3, 4]])

In [39]:
# Create a 1D array
a = np.array([1, 2, 3, 4, 5,6,7,8])
a.shape

(8,)

In [46]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [45]:
c = a[:, np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# indexing and slicing 

In [47]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[]

array([5, 6])

In [52]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
b[b<11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [59]:
# filter odd numbers
b[b % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [60]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# use three conditions and filter the array 
b[(b > 2) & (b < 11) & (b % 2 ==0)]

array([ 4,  6,  8, 10])

In [62]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])