# Numpy indexing and slicing

In [2]:
import numpy as np 

In [3]:
# create an array 
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a[1:5]

array([2, 3, 4, 5])

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

np.int64(4)

In [7]:
c = b.reshape(3, 2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [8]:
c[0]

array([0, 2])

In [9]:
c[(c < 5) & (c>7)]
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# Enlist boolean operator conditional operators

# Making an array from a data or another array

In [10]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [12]:
len(a)

45

In [14]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

# Matrix or Matrices 

In [15]:
# create a 2x3 matrix
a = np.array ([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# create a matrix
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [1]:
# slicing a matrix
b[1:3, 3:5] 

NameError: name 'b' is not defined

In [ ]:
a = 